site_name: World End Lizard
site_url: https://rodrigowright.github.io/world-end-lizard/
site_author: Rodrigo Wright
site_description: >-
  Be Happy (:
docs_dir: './docs/'                           # Where to find the English markdown files
site_dir: './generator/'                      # Where to put the English HTML files
repo_url: https://github.com/RodrigoWright/world-end-lizard
repo_name: world-end-lizard

nav:
  - Home: index.md
  - About: about.md

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: pt-BR
          name: Português
          build: true
  - git-revision-date-localized:
      enable_creation_date: true

theme: 
  name: material
  favicon: img/favicon.png
  logo: img/favicon.png
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle: 
        icon: material/brightness-7
        name: Light Side
      primary: black
      accent: red

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-3
        name: Dark Side
      primary: black
      accent: deep orange

  features:
#    - navigation.instant
#    - navigation.instant.progress
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - search.suggest  
    - search.highlights
    - search.share

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RodrigoWright
      name: Rodrigo Wright on Github
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rodrigo-edmar-wright-dos-santos-ab00841ab
      name: Rodrigo Wright on LinkeIN
  generator: false      
# Language Selection

copyright: Copyright &copy; 2024 Rodrigo Wright